### ISSUE TITLE
Specifications on GPU

### ISSUE THREAD

**Issue by JackieHanLab** [RL4M/IRENE#2]
Hi there, I'm curious what specific GPU did you use? As I tried out with your code on Nvidia Tesla V100 (32G memory), OOM occurs easily even with 224x224-image-only and batch size 2. In contrast, you seem to allocate 16 entries to each GPU. If this difference is hard to explain, I request release of the training code you actually used.
Thx.

**Comment by JackieHanLab** [comment]
> Hi there, I'm curious what specific GPU did you use? As I tried out with your code on Nvidia Tesla V100 (32G memory), OOM occurs easily even with 224x224-image-only and batch size 2. In contrast, you seem to allocate 16 entries to each GPU. If this difference is hard to explain, I request release of the training code you actually used. Thx.

Oh, it's 256 on 4 GPUs for training, even larger batch size, according your NBE paper.

**Comment by funnyzhou** [comment]
Hi,
You can try mixed precision training. I used four V100, each with 32G memory. Without mixed precision training, each V100 card can store a batch of 32 samples.

**Comment by JackieHanLab** [comment]
> Hi, You can try mixed precision training. I used four V100, each with 32G memory. Without mixed precision training, each V100 card can store a batch of 32 samples.

Turns out I set a dummy variable with high dimension, which incurred OOM during attention calculation. And I'm applying amp, thank you for your kind reply.
